config/routes.rb
Rails.application.routes.draw do
  resources :forsales

end

app/models/forsale.rb
class Forsale < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forsales_controller.rb
class ForsalesController < ApplicationController
  before_action :set_forsale, only: [:show, :edit, :update, :destroy]

  # GET /forsales
  # GET /forsales.json
  def index
    @forsales = Forsale.all
  end

  # GET /forsales/1
  # GET /forsales/1.json
  def show
  end

  # GET /forsales/new
  def new
    @forsale = Forsale.new
  end

  # GET /forsales/1/edit
  def edit
  end

  # POST /forsales
  # POST /forsales.json
  def create
    @forsale = Forsale.new(forsale_params)

    respond_to do |format|
      if @forsale.save
        format.html { redirect_to @forsale, notice: 'Forsale was successfully created.' }
        format.json { render :show, status: :created, location: @forsale }
      else
        format.html { render :new }
        format.json { render json: @forsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forsales/1
  # PATCH/PUT /forsales/1.json
  def update
    respond_to do |format|
      if @forsale.update(forsale_params)
        format.html { redirect_to @forsale, notice: 'Forsale was successfully updated.' }
        format.json { render :show, status: :ok, location: @forsale }
      else
        format.html { render :edit }
        format.json { render json: @forsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forsales/1
  # DELETE /forsales/1.json
  def destroy
    @forsale.destroy
    respond_to do |format|
      format.html { redirect_to forsales_url, notice: 'Forsale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forsale
      @forsale = Forsale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forsale_params
      params.require(:forsale).permit(:name, :address, :longitude, :latitude, :gmaps, :city, :postal_code, :province, :description, :house_type, :style, :year_build, :lot_size, :size, :lot_type, :bedrooms, :bathroom, :ext_finish, :heating_type, :heating_fuel, :cooling_type, :water, :parking_type, :total_parking_space, :liv_room, :din_room, :kitchen, :part_bathroom, :eating_area, :mas_bedroom, :bedroom_2, :bedroom_3, :bedroom_4, :bedroom_5, :bathroom, :bathroom_2, :bathroom_3, :laundry_room, :rec_room, :mls, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forsales_helper.rb
module ForsalesHelper
end

app/views/forsales/_form.html.erb
<%= simple_form_for @forsale do |f| %>
  <% if @forsale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forsale.errors.count, "error") %> prohibited this forsale from being saved:</h2>

      <ul>
      <% @forsale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.input :name , wrapper_html: { class: 'ui-field-contain' } %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br>
    <%= f.check_box :gmaps %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :house_type %><br>
    <%= f.text_field :house_type %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :year_build %><br>
    <%= f.number_field :year_build %>
  </div>
  <div class="field">
    <%= f.label :lot_size %><br>
    <%= f.text_field :lot_size %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :lot_type %><br>
    <%= f.text_field :lot_type %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.number_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.number_field :bathroom %>
  </div>
  <div class="field">
    <%= f.label :ext_finish %><br>
    <%= f.text_field :ext_finish %>
  </div>
  <div class="field">
    <%= f.label :heating_type %><br>
    <%= f.text_field :heating_type %>
  </div>
  <div class="field">
    <%= f.label :heating_fuel %><br>
    <%= f.text_field :heating_fuel %>
  </div>
  <div class="field">
    <%= f.label :cooling_type %><br>
    <%= f.text_field :cooling_type %>
  </div>
  <div class="field">
    <%= f.label :water %><br>
    <%= f.text_field :water %>
  </div>
  <div class="field">
    <%= f.label :parking_type %><br>
    <%= f.text_field :parking_type %>
  </div>
  <div class="field">
    <%= f.label :total_parking_space %><br>
    <%= f.number_field :total_parking_space %>
  </div>
  <div class="field">
    <%= f.label :liv_room %><br>
    <%= f.text_field :liv_room %>
  </div>
  <div class="field">
    <%= f.label :din_room %><br>
    <%= f.text_field :din_room %>
  </div>
  <div class="field">
    <%= f.label :kitchen %><br>
    <%= f.text_field :kitchen %>
  </div>
  <div class="field">
    <%= f.label :part_bathroom %><br>
    <%= f.text_field :part_bathroom %>
  </div>
  <div class="field">
    <%= f.label :eating_area %><br>
    <%= f.text_field :eating_area %>
  </div>
  <div class="field">
    <%= f.label :mas_bedroom %><br>
    <%= f.text_field :mas_bedroom %>
  </div>
  <div class="field">
    <%= f.label :bedroom_2 %><br>
    <%= f.text_field :bedroom_2 %>
  </div>
  <div class="field">
    <%= f.label :bedroom_3 %><br>
    <%= f.text_field :bedroom_3 %>
  </div>
  <div class="field">
    <%= f.label :bedroom_4 %><br>
    <%= f.text_field :bedroom_4 %>
  </div>
  <div class="field">
    <%= f.label :bedroom_5 %><br>
    <%= f.text_field :bedroom_5 %>
  </div>
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.text_field :bathroom %>
  </div>
  <div class="field">
    <%= f.label :bathroom_2 %><br>
    <%= f.text_field :bathroom_2 %>
  </div>
  <div class="field">
    <%= f.label :bathroom_3 %><br>
    <%= f.text_field :bathroom_3 %>
  </div>
  <div class="field">
    <%= f.label :laundry_room %><br>
    <%= f.text_field :laundry_room %>
  </div>
  <div class="field">
    <%= f.label :rec_room %><br>
    <%= f.text_field :rec_room %>
  </div>
  <div class="field">
    <%= f.label :mls %><br>
    <%= f.number_field :mls %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forsales/edit.html.erb
<h1>Editing forsale</h1>

<%= render 'form' %>

<%= link_to 'Show', @forsale %> |
<%= link_to 'Back', forsales_path %>

app/views/forsales/index.html.erb
<h1>Listing forsales</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Gmaps</th>
      <th>City</th>
      <th>Postal code</th>
      <th>Province</th>
      <th>Description</th>
      <th>House type</th>
      <th>Style</th>
      <th>Year build</th>
      <th>Lot size</th>
      <th>Size</th>
      <th>Lot type</th>
      <th>Bedrooms</th>
      <th>Bathroom</th>
      <th>Ext finish</th>
      <th>Heating type</th>
      <th>Heating fuel</th>
      <th>Cooling type</th>
      <th>Water</th>
      <th>Parking type</th>
      <th>Total parking space</th>
      <th>Liv room</th>
      <th>Din room</th>
      <th>Kitchen</th>
      <th>Part bathroom</th>
      <th>Eating area</th>
      <th>Mas bedroom</th>
      <th>Bedroom 2</th>
      <th>Bedroom 3</th>
      <th>Bedroom 4</th>
      <th>Bedroom 5</th>
      <th>Bathroom</th>
      <th>Bathroom 2</th>
      <th>Bathroom 3</th>
      <th>Laundry room</th>
      <th>Rec room</th>
      <th>Mls</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forsales.each do |forsale| %>
      <tr>
        <td><%= forsale.name %></td>
        <td><%= forsale.address %></td>
        <td><%= forsale.longitude %></td>
        <td><%= forsale.latitude %></td>
        <td><%= forsale.gmaps %></td>
        <td><%= forsale.city %></td>
        <td><%= forsale.postal_code %></td>
        <td><%= forsale.province %></td>
        <td><%= forsale.description %></td>
        <td><%= forsale.house_type %></td>
        <td><%= forsale.style %></td>
        <td><%= forsale.year_build %></td>
        <td><%= forsale.lot_size %></td>
        <td><%= forsale.size %></td>
        <td><%= forsale.lot_type %></td>
        <td><%= forsale.bedrooms %></td>
        <td><%= forsale.bathroom %></td>
        <td><%= forsale.ext_finish %></td>
        <td><%= forsale.heating_type %></td>
        <td><%= forsale.heating_fuel %></td>
        <td><%= forsale.cooling_type %></td>
        <td><%= forsale.water %></td>
        <td><%= forsale.parking_type %></td>
        <td><%= forsale.total_parking_space %></td>
        <td><%= forsale.liv_room %></td>
        <td><%= forsale.din_room %></td>
        <td><%= forsale.kitchen %></td>
        <td><%= forsale.part_bathroom %></td>
        <td><%= forsale.eating_area %></td>
        <td><%= forsale.mas_bedroom %></td>
        <td><%= forsale.bedroom_2 %></td>
        <td><%= forsale.bedroom_3 %></td>
        <td><%= forsale.bedroom_4 %></td>
        <td><%= forsale.bedroom_5 %></td>
        <td><%= forsale.bathroom %></td>
        <td><%= forsale.bathroom_2 %></td>
        <td><%= forsale.bathroom_3 %></td>
        <td><%= forsale.laundry_room %></td>
        <td><%= forsale.rec_room %></td>
        <td><%= forsale.mls %></td>
        <td><%= forsale.price %></td>
        <td><%= link_to 'Show', forsale %></td>
        <td><%= link_to 'Edit', edit_forsale_path(forsale) %></td>
        <td><%= link_to 'Destroy', forsale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Forsale', new_forsale_path %>

app/views/forsales/new.html.erb
<h1>New forsale</h1>

<%= render 'form' %>

<%= link_to 'Back', forsales_path %>

app/views/forsales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forsale.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @forsale.address %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @forsale.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @forsale.latitude %>
</p>

<p>
  <strong>Gmaps:</strong>
  <%= @forsale.gmaps %>
</p>

<p>
  <strong>City:</strong>
  <%= @forsale.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @forsale.postal_code %>
</p>

<p>
  <strong>Province:</strong>
  <%= @forsale.province %>
</p>

<p>
  <strong>Description:</strong>
  <%= @forsale.description %>
</p>

<p>
  <strong>House type:</strong>
  <%= @forsale.house_type %>
</p>

<p>
  <strong>Style:</strong>
  <%= @forsale.style %>
</p>

<p>
  <strong>Year build:</strong>
  <%= @forsale.year_build %>
</p>

<p>
  <strong>Lot size:</strong>
  <%= @forsale.lot_size %>
</p>

<p>
  <strong>Size:</strong>
  <%= @forsale.size %>
</p>

<p>
  <strong>Lot type:</strong>
  <%= @forsale.lot_type %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @forsale.bedrooms %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @forsale.bathroom %>
</p>

<p>
  <strong>Ext finish:</strong>
  <%= @forsale.ext_finish %>
</p>

<p>
  <strong>Heating type:</strong>
  <%= @forsale.heating_type %>
</p>

<p>
  <strong>Heating fuel:</strong>
  <%= @forsale.heating_fuel %>
</p>

<p>
  <strong>Cooling type:</strong>
  <%= @forsale.cooling_type %>
</p>

<p>
  <strong>Water:</strong>
  <%= @forsale.water %>
</p>

<p>
  <strong>Parking type:</strong>
  <%= @forsale.parking_type %>
</p>

<p>
  <strong>Total parking space:</strong>
  <%= @forsale.total_parking_space %>
</p>

<p>
  <strong>Liv room:</strong>
  <%= @forsale.liv_room %>
</p>

<p>
  <strong>Din room:</strong>
  <%= @forsale.din_room %>
</p>

<p>
  <strong>Kitchen:</strong>
  <%= @forsale.kitchen %>
</p>

<p>
  <strong>Part bathroom:</strong>
  <%= @forsale.part_bathroom %>
</p>

<p>
  <strong>Eating area:</strong>
  <%= @forsale.eating_area %>
</p>

<p>
  <strong>Mas bedroom:</strong>
  <%= @forsale.mas_bedroom %>
</p>

<p>
  <strong>Bedroom 2:</strong>
  <%= @forsale.bedroom_2 %>
</p>

<p>
  <strong>Bedroom 3:</strong>
  <%= @forsale.bedroom_3 %>
</p>

<p>
  <strong>Bedroom 4:</strong>
  <%= @forsale.bedroom_4 %>
</p>

<p>
  <strong>Bedroom 5:</strong>
  <%= @forsale.bedroom_5 %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @forsale.bathroom %>
</p>

<p>
  <strong>Bathroom 2:</strong>
  <%= @forsale.bathroom_2 %>
</p>

<p>
  <strong>Bathroom 3:</strong>
  <%= @forsale.bathroom_3 %>
</p>

<p>
  <strong>Laundry room:</strong>
  <%= @forsale.laundry_room %>
</p>

<p>
  <strong>Rec room:</strong>
  <%= @forsale.rec_room %>
</p>

<p>
  <strong>Mls:</strong>
  <%= @forsale.mls %>
</p>

<p>
  <strong>Price:</strong>
  <%= @forsale.price %>
</p>

<%= link_to 'Edit', edit_forsale_path(@forsale) %> |
<%= link_to 'Back', forsales_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Listing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	
	<div data-role="page">

	<div data-role="panel" id="mypanel">
	    <ul>
	        <li><%= link_to 'View all listing', forsales_path %></li>
	        <li><%= link_to 'Add new listing', new_forsale_path %></li>
	        <li><a href="#">Three</a></li>
	    </ul>
	</div><!-- /panel -->

	<div data-role="header"><a  href="#mypanel"class="ui-btn-left ui-btn ui-mini ui-btn-icon-left ui-btn-icon-notext ui-corner-all ui-icon-bars"></a>
	    <span class="ui-title">My Listings</span></div>
	<div role="main" class="ui-content">
	<%= yield %></div>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<div data-role="footer"><h4>footer</h4></div>

	</div><!-- page -->
	


</body>
</html>